#DB Verbindung

spring:
  datasource:

    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       # use-new-id-generator-mappings: false
        jdbc:
          time_zone: UTC
    show-sql: false # Set true for debugging - Shows SQL Queries!
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # (DB table structure actualization) options:create, create-drop, validate, update-)
    open-in-view: false
  sql:
    init:
      platform: mysql
      mode: always
security:
  jwt:
    secret: ${JWT_SECRET}
#    expiration-in-ms: ${JWT_EXPIRATION_IN_MS}